[env:esp32-s3-devkitc-1]
platform = espressif32
board = lolin_s3_mini
framework = arduino

# Hardware Settings
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_build.flash_size = 4MB

# Serial Monitor & Upload
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.usbmodem113101
monitor_port = /dev/cu.usbmodem113101

# Build Flags
build_flags = 
    -D PIN_LED=48
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MSC_ON_BOOT=0
    -D ARDUINO_USB_DFU_ON_BOOT=0
    -D CORE_DEBUG_LEVEL=3


# Required Libraries
lib_deps =
    WiFi
    WebServer
    ESPmDNS
    adafruit/Adafruit NeoPixel

# Optimization & Debugging
build_type = release
check_tool = cppcheck
